version: '3.1'

services:
  
  db:
    container_name: dumpadb
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - dumpadb:/var/lib/mysql
      - ./mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/init/create_test_db.sql:/docker-entrypoint-initdb.d/create_test_db.sql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  dumpadb:
